name: Package and Release Maven Project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: TheJordanDev/Epsi-BDE-Plugin
      TAG_NAME: ${{github.head_ref}}
    steps:
      - uses: actions/checkout@v2
      - name: "🏷️ Push tag"
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{env.TAG_NAME}}
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with: 
          files: ./target/Epsi-1.0-SNAPSHOT.jar
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{env.TAG_NAME}}
