name: Package and Release Maven Project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: TheJordanDev/Epsi-BDE-Plugin
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package
      - name: Get current time
        id: time
        run: echo "::set-output name=time::$(TZ='France/Paris' date +'%d-%m-%Y %T')"
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with: 
          files: ./target/Epsi-1.0-SNAPSHOT.jar
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: 'release'
          name: ${{ steps.time.outputs.time }}
